// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace StalkCitizen.Clients.DigitalPost.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MessageAttachment
    {
        /// <summary>
        /// Initializes a new instance of the MessageAttachment class.
        /// </summary>
        public MessageAttachment()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MessageAttachment class.
        /// </summary>
        /// <param name="referenceId">Identifier of the uploaded file</param>
        /// <param name="fileName">Name of the file</param>
        public MessageAttachment(System.Guid? referenceId = default(System.Guid?), string fileName = default(string))
        {
            ReferenceId = referenceId;
            FileName = fileName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets identifier of the uploaded file
        /// </summary>
        [JsonProperty(PropertyName = "referenceId")]
        public System.Guid? ReferenceId { get; set; }

        /// <summary>
        /// Gets or sets name of the file
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

    }
}
