// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace StalkCitizen.Clients.DigitalPost.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UploadAttachmentResponse
    {
        /// <summary>
        /// Initializes a new instance of the UploadAttachmentResponse class.
        /// </summary>
        public UploadAttachmentResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UploadAttachmentResponse class.
        /// </summary>
        public UploadAttachmentResponse(System.Guid? referenceId = default(System.Guid?))
        {
            ReferenceId = referenceId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referenceId")]
        public System.Guid? ReferenceId { get; set; }

    }
}
